### ISSUE TITLE
R-021: Cartas de recomendación

### ISSUE THREAD

**Issue by juamarcan8** [ISPP-GRUPO-8/BANQUETBUDDY#115]
### Descripción de la funcionalidad. (Misma descripción que en el product backlog)

Los empleados pueden recibir cartas de recomendación dentro de la página de los caterings para los que ya haya trabajado

### Contexto adicional

En el perfil del empleado aparecen las cartas de recomendación hechas por los caterings

**Comment by juamarcan8** [comment]
Se va a crear un hotfix debido a la necesidad de modificar el modelo de datos ya que falta un atributo que relacione los trabajadores con las cartas de recomendación

**Comment by javierrc8** [comment]
Se ha eliminado del modelo la relación de TaskEmployee, ya que Django realiza esta relación automáticamente. Al añadirlo manualmente se duplicaba esta tabla.
