### ISSUE TITLE
R-046: Opiniones y reportes

### ISSUE THREAD

**Issue by alvcarber1** [ISPP-GRUPO-8/BANQUETBUDDY#191]
### Descripción de la funcionalidad. (Misma descripción que en el product backlog)

Las empresas de catering deben obtener información valiosa sobre su rendimiento y generar reportes con datos estadísticos.

### Contexto adicional

Después de cada evento de catering, los clientes deben poder dejar comentarios y calificaciones sobre el servicio recibido, con la capacidad para que las empresas vean y respondan a estos comentarios de manera efectiva.

**Comment by javierrc8** [comment]
Finalmente, se ha decidido entre todo el grupo, cancelar este nuevo incremento. Por lo que se cierra la issue.
