### ISSUE TITLE
F018-SU1: Tests de vista

### ISSUE THREAD

**Issue by alvcarber1** [ISPP-GRUPO-8/BANQUETBUDDY#231]
### Descripción de la funcionalidad. (Misma descripción que en el product backlog)

Hacer tests de vista para las funcionalidades implementadas para el grupo 1, que incluye lo siguiente:

Reserva de caterings
Inicio de Sesión de Usuario
Edición de Eventos
Cancelación de Eventos

**Comment by javierrc8** [comment]
Se ha realizado test de vista para la funcionalidad de cierre de sesión.
