### ISSUE TITLE
R-052: Proceso de Contratación de Catering

### ISSUE THREAD

**Issue by juamarcan8** [ISPP-GRUPO-8/BANQUETBUDDY#47]
Los usuarios particulares deben poder seleccionar y contratar servicios de catering, especificando detalles como fecha, número de invitados y menú.

**Comment by javierrc8** [comment]
Ya se ha implementado parte de la funcionalidad. Recomiendo revisar la parte de Frontend de esta, así como la posibilidad de permitir al usuario visualizar sus reservas. Además, faltaría por restringir la funcionalidad solo a los usuarios particular.
